import { Exercise } from "./types";
export const exercises: Exercise[] = [
  {
    id: "side-plank",
    name: "Side Plank",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["obliques", "isometric", "core-stability"],
    description:
      "Lie on your side, lift hips off the ground, maintain a straight line from head to feet, supporting on one arm.",
    targetMuscleGroups: ["Obliques", "Core", "Shoulders", "Glutes"],
    bodyRegion: "core",
    mistakes: ["Hips sagging", "Rotating torso", "Neck misalignment"],
    progression: [], // beginner already
    unitPoint: 0.4,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "leg-raises",
    name: "Leg Raises",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["lower-abs", "bodyweight", "core"],
    description:
      "Lie on your back, lift legs toward the ceiling while keeping lower back pressed to the floor, then slowly lower.",
    targetMuscleGroups: ["Lower Abs", "Hip Flexors", "Core"],
    bodyRegion: "core",
    mistakes: [
      "Arching lower back",
      "Swinging legs",
      "Not controlling descent",
    ],
    progression: ["bent-knee-leg-raises"], // easier
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "burpees",
    name: "Burpees",
    level: "intermediate",
    measurement: "reps",
    type: "conditioning",
    movementPattern: "full-body",
    tags: ["explosive", "cardio", "bodyweight", "full-body"],
    bodyRegion: "full-body",
    description:
      "From standing, drop into a squat, kick feet back into a push-up, return to squat, then jump up explosively.",
    targetMuscleGroups: ["Legs", "Core", "Chest", "Shoulders", "Arms"],
    mistakes: [
      "Not going full range",
      "Poor landing mechanics",
      "Sagging hips during plank portion",
    ],
    progression: ["squat-thrusts"], // easier version
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "jump-squats",
    name: "Jump Squats",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["explosive", "legs", "plyometric", "bodyweight"],
    description:
      "Perform a squat and explode upwards into a jump, landing softly and returning to squat position.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Calves"],
    bodyRegion: "lower-body",
    mistakes: [
      "Knees collapsing inward",
      "Landing stiffly",
      "Shallow squat depth",
    ],
    progression: ["air-squat"], // easier version
    unitPoint: 0.75,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "pullup",
    name: "Pull-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["upper-body", "back", "arms", "bodyweight", "vertical-pull"],
    description:
      "From a dead hang, pull your chin over the bar using an overhand grip, keeping core tight.",
    targetMuscleGroups: ["Back", "Biceps", "Shoulders", "Core"],
    bodyRegion: "upper-body",
    mistakes: ["Kipping/momentum", "Partial range", "Shrugging shoulders"],
    progression: ["assisted-pull-up", "band-assisted-pull-up"],
    unitPoint: 3,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "chin-up",
    name: "Chin-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["upper-body", "back", "biceps", "bodyweight", "vertical-pull"],
    bodyRegion: "upper-body",
    description:
      "From a dead hang, pull your chin over the bar using an underhand grip, keeping core tight.",
    targetMuscleGroups: ["Biceps", "Back", "Shoulders", "Core"],
    mistakes: ["Elbow flaring", "Jerky motion", "Partial range"],
    progression: ["negative-chin-up", "assisted-chin-up"],
    unitPoint: 2.5,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "pushup",
    name: "Push-up",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["bodyweight", "upper-body", "horizontal-push", "core-stability"],
    bodyRegion: "upper-body",
    description:
      "Keep your core tight, body in a straight line, and elbows at about a 45-degree angle as you lower and push up.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    mistakes: [
      "Sagging hips",
      "Flared elbows",
      "Partial range of motion",
      "Head dropping or neck craned forward",
    ],
    progression: ["knee-push-up", "incline-push-up", "diamond-push-up"], // easier → standard → harder variations
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "squat",
    name: "Squat",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["bodyweight", "lower-body", "knee-dominant", "mobility"],
    bodyRegion: "lower-body",
    description:
      "Keep your chest up and back neutral as you lower your hips until your thighs are parallel to the ground.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    mistakes: [
      "Knees collapsing inward",
      "Heels lifting off the ground",
      "Rounded lower back",
      "Shallow depth",
    ],
    progression: ["assisted-wall-squat", "box-squat"], // easier variations
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "deadhang",
    name: "Dead Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["grip", "shoulder-health", "scapular-control", "isometric"],
    bodyRegion: "upper-body",
    description:
      "Hang from the bar with straight arms, relaxed shoulders, and controlled breathing.",
    targetMuscleGroups: ["Forearms", "Grip", "Shoulders"],
    mistakes: [
      "Shrugging shoulders excessively",
      "Bending the arms",
      "Holding breath",
      "Losing grip due to poor hand placement",
    ],
    progression: ["scapular-hang"], // easier scapular-focused hang before full dead hang
    unitPoint: 0.23,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "plank",
    name: "Plank",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "isometric", "anti-extension", "spine-stability"],
    bodyRegion: "core",
    description:
      "Maintain a straight line from head to heels while keeping your core tight and hips level.",
    targetMuscleGroups: ["Core", "Shoulders", "Glutes"],
    mistakes: [
      "Sagging hips",
      "Piking hips too high",
      "Holding breath",
      "Neck not aligned with spine",
    ],
    progression: ["knee-plank", "elbow-plank", "side-plank"], // easier → standard → advanced variations
    unitPoint: 0.33,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "horse-stance",
    name: "Horse Stance",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "legs",
    tags: ["isometric", "lower-body", "stance", "mobility"],
    bodyRegion: "lower-body",
    description:
      "Stand with feet wider than shoulders, knees bent, hips low, and back straight. Hold the position.",
    targetMuscleGroups: [
      "Quadriceps",
      "Glutes",
      "Hamstrings",
      "Adductors",
      "Core",
    ],
    mistakes: [
      "Knees collapsing inward",
      "Back rounding",
      "Feet too close together",
      "Leaning forward",
    ],
    progression: ["wall-squat", "deeper-horse-stance", "weighted-horse-stance"],
    unitPoint: 0.16,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "one-arm-pushup",
    name: "One-Arm Push-up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: [
      "bodyweight",
      "upper-body",
      "horizontal-push",
      "core-stability",
      "strength",
    ],
    description:
      "Perform a push-up using one arm while keeping your body aligned. The other arm may rest on your back or side for balance.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    bodyRegion: "upper-body",
    mistakes: [
      "Hip sagging",
      "Rotating torso excessively",
      "Partial range of motion",
      "Elbow flaring",
    ],
    progression: ["archer-pushup", "uneven-pushup", "assisted-one-arm-pushup"],
    unitPoint: 3.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "archer-pushup",
    name: "Archer Push-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: [
      "bodyweight",
      "upper-body",
      "horizontal-push",
      "core-stability",
      "strength",
    ],
    description:
      "Perform a push-up while extending one arm straight to the side, shifting most weight to the other arm.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    bodyRegion: "upper-body",
    mistakes: [
      "Sagging hips",
      "Elbow flaring",
      "Partial range",
      "Rotating torso",
    ],
    progression: ["standard-pushup", "incline-archer-pushup", "one-arm-pushup"],
    unitPoint: 1.8,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "diamond-pushup",
    name: "Diamond Push-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["bodyweight", "upper-body", "horizontal-push", "triceps-focus"],
    bodyRegion: "upper-body",
    description:
      "Place your hands close together under your chest forming a diamond shape with thumbs and index fingers. Lower and push up keeping elbows close.",
    targetMuscleGroups: ["Triceps", "Chest", "Shoulders", "Core"],
    mistakes: [
      "Elbow flaring",
      "Sagging hips",
      "Partial range",
      "Head dropping",
    ],
    progression: ["standard-pushup", "close-grip-pushup", "archer-pushup"],
    unitPoint: 1.3,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "human-flag",
    name: "Human Flag",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "obliques", "bodyweight", "flag", "advanced-skill"],
    bodyRegion: "full-body",
    description:
      "Grip a vertical pole and hold your body horizontally, parallel to the ground, using obliques, lats, and core.",
    targetMuscleGroups: ["Obliques", "Lats", "Shoulders", "Core", "Forearms"],
    mistakes: ["Sagging legs", "Bent arms", "Arching back", "Grip failure"],
    progression: [
      "vertical-pole-hang",
      "tuck-human-flag",
      "straddle-human-flag",
    ],
    unitPoint: 3.3,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "bodyweight", "isometric", "anti-extension", "abs"],
    bodyRegion: "core",
    description:
      "Lie on your back, lift your legs and shoulders slightly off the ground, keep lower back pressed into the floor, arms extended overhead.",
    targetMuscleGroups: ["Core", "Hip Flexors", "Shoulders"],
    mistakes: ["Arching lower back", "Raising legs too high", "Neck tension"],
    progression: ["tuck-hollow-hold", "single-leg-hollow-hold"],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "stability", "bodyweight", "anti-extension"],
    bodyRegion: "core",
    description:
      "Lie on your back with arms extended toward the ceiling and knees bent at 90°. Slowly lower opposite arm and leg toward the floor while keeping your lower back pressed into the ground, then return to start. Alternate sides.",
    targetMuscleGroups: [
      "Core",
      "Rectus Abdominis",
      "Obliques",
      "Hip Flexors",
      "Lower Back",
    ],
    mistakes: [
      "Lower back arching off the floor",
      "Rushing the movement instead of controlled",
      "Neck straining",
    ],
    progression: [
      "dead-bug-arm-only",
      "dead-bug-leg-only",
      "weighted-dead-bug",
    ],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "explosive",
    tags: ["core", "cardio", "bodyweight", "full-body"],
    bodyRegion: "full-body",
    description:
      "From a plank position, alternate driving knees toward your chest at a quick pace while keeping core tight.",
    targetMuscleGroups: [
      "Core",
      "Shoulders",
      "Hip Flexors",
      "Chest",
      "Triceps",
    ],
    mistakes: [
      "Hips too high or low",
      "Bouncing excessively",
      "Poor arm alignment",
    ],
    progression: ["slow-mountain-climbers", "high-knees-mountain-climbers"],
    unitPoint: 0.7,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "muscle-up",
    name: "Muscle-up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["upper-body", "bodyweight", "pull", "explosive", "bar"],
    bodyRegion: "upper-body",
    description:
      "Pull up explosively over a bar and transition into a dip position at the top.",
    targetMuscleGroups: [
      "Back",
      "Biceps",
      "Chest",
      "Shoulders",
      "Triceps",
      "Core",
    ],
    mistakes: [
      "Kipping excessively",
      "Partial range of motion",
      "Elbows flaring",
      "Lack of control on descent",
    ],
    progression: ["pull-up", "chest-to-bar pull-up", "explosive pull-up"],
    unitPoint: 5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "sissy-squat",
    name: "Sissy Squat",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["quadriceps", "bodyweight", "knee-dominant"],
    bodyRegion: "lower-body",
    description:
      "Lean back while keeping hips extended and knees forward, lowering your body, and then return upright.",
    targetMuscleGroups: ["Quadriceps", "Core"],
    mistakes: [
      "Leaning too far back",
      "Knees collapsing",
      "Arching lower back",
    ],
    progression: ["assisted-sissy-squat", "wall-squat"],
    unitPoint: 0.75,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "pistol-squat",
    name: "Pistol Squat",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["bodyweight", "single-leg", "mobility", "strength"],
    description:
      "Squat on one leg while the other leg is extended in front, lowering until the thigh is parallel to the floor.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    bodyRegion: "lower-body",
    mistakes: [
      "Knee valgus",
      "Leaning forward",
      "Rounding back",
      "Loss of balance",
    ],
    progression: [
      "assisted-pistol-squat",
      "box-pistol-squat",
      "partial-range-pistol",
    ],
    unitPoint: 1.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "knee-raise",
    name: "Knee Raise",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["abs", "bodyweight", "pull", "hanging"],
    bodyRegion: "core",
    description:
      "Hang from a bar and lift knees toward your chest using your core muscles.",
    targetMuscleGroups: ["Lower Abs", "Hip Flexors", "Grip", "Forearms"],
    mistakes: ["Swinging body", "Not controlling legs", "Arching back"],
    progression: ["tuck-knee-raise", "single-leg-knee-raise"],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "elevated-pike-hold",
    name: "Elevated Pike Hold",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "bodyweight", "isometric", "shoulder-stability"],
    bodyRegion: "core",
    description:
      "Place feet on an elevated surface and hands on the floor, forming an inverted 'V'. Hold the position while keeping shoulders and core tight.",
    targetMuscleGroups: ["Shoulders", "Core", "Glutes", "Hamstrings"],
    mistakes: ["Sagging hips", "Bent arms", "Rounded back"],
    progression: [
      "regular-pike-hold",
      "elevated-pike-hold",
      "pike-to-handstand-progressions",
    ],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "incline-pushup",
    name: "Incline Push-up",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["upper-body", "bodyweight", "horizontal-push", "beginner-friendly"],
    bodyRegion: "upper-body",
    description:
      "Hands on an elevated surface, perform a push-up while keeping core tight and elbows at 45 degrees.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    mistakes: ["Sagging hips", "Partial range", "Flared elbows"],
    progression: ["wall-pushup", "incline-pushup", "standard-pushup"],
    unitPoint: 0.7,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "dips",
    name: "Dips",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: [
      "upper-body",
      "bodyweight",
      "vertical-push",
      "triceps-focus",
      "chest",
    ],
    bodyRegion: "upper-body",
    description:
      "Lower your body between parallel bars until shoulders are below elbows, then push back up.",
    targetMuscleGroups: ["Triceps", "Chest", "Shoulders", "Core"],
    mistakes: [
      "Elbows flaring",
      "Swinging body",
      "Partial range",
      "Leaning too far forward",
    ],
    progression: ["bench-dip", "assisted-dip", "full-dip"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "rope-skip",
    name: "Rope Skip",
    level: "beginner",
    measurement: "reps",
    type: "cardio",
    movementPattern: "explosive",
    tags: ["full-body", "cardio", "plyometric", "coordination"],
    bodyRegion: "full-body",
    description:
      "Jump over a rope continuously, landing softly on your feet and maintaining rhythm.",
    targetMuscleGroups: [
      "Calves",
      "Quads",
      "Glutes",
      "Shoulders",
      "Forearms",
      "Core",
    ],
    mistakes: ["Bouncing excessively", "Poor timing", "Rounding shoulders"],
    progression: [
      "low-speed-rope-skip",
      "alternating-feet-skip",
      "double-unders",
    ],
    unitPoint: 0.1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "active-hang",
    name: "Active Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["grip", "shoulder-health", "scapular-control", "bodyweight"],
    bodyRegion: "upper-body",
    description:
      "Hang from a bar while engaging the shoulders (pulling them down and back) and keeping core tight.",
    targetMuscleGroups: ["Shoulders", "Lats", "Forearms", "Core"],
    mistakes: ["Shrugging shoulders", "Bent elbows", "Loose core"],
    progression: ["scapular-hang", "dead-hang"],
    unitPoint: 0.33,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "passive-hang",
    name: "Passive Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["grip", "shoulder-relaxation", "bodyweight"],
    bodyRegion: "upper-body",
    description:
      "Hang from a bar with relaxed shoulders and arms fully extended, allowing the body to hang freely.",
    targetMuscleGroups: ["Forearms", "Shoulders", "Grip"],
    mistakes: ["Tensing shoulders", "Bent arms", "Swinging"],
    progression: ["dead-hang", "active-hang"],
    unitPoint: 0.23,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "front-support",
    name: "Front Support",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "shoulders", "triceps", "support-hold"],
    bodyRegion: "upper-body",
    description:
      "Hold yourself on parallel bars or floor in a straight-arm position with tight core and neutral spine.",
    targetMuscleGroups: ["Core", "Shoulders", "Triceps", "Chest"],
    mistakes: ["Sagging hips", "Bent elbows", "Rounded shoulders"],
    progression: ["knee-front-support", "elevated-front-support"],
    unitPoint: 0.33,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "side-support",
    name: "Side Support",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "obliques", "support-hold"],
    bodyRegion: "upper-body",
    description:
      "Hold yourself on one hand or elbow in a straight-arm side support position, keeping hips lifted.",
    targetMuscleGroups: ["Obliques", "Shoulders", "Core", "Glutes"],
    mistakes: ["Hips sagging", "Twisting torso", "Bent arm"],
    progression: ["knee-side-support", "elevated-side-support"],
    unitPoint: 0.37,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "back-support",
    name: "Back Support",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "posterior-chain", "support-hold"],
    bodyRegion: "upper-body",
    description:
      "Hold your body on hands and feet facing up, keeping shoulders, glutes, and core engaged.",
    targetMuscleGroups: ["Back", "Glutes", "Shoulders", "Core"],
    mistakes: ["Sagging hips", "Loose core", "Rounded shoulders"],
    progression: ["knee-back-support", "elevated-back-support"],
    unitPoint: 0.3,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "vertical-support",
    name: "Vertical Support",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "shoulders", "arms", "support-hold"],
    bodyRegion: "upper-body",
    description:
      "Support your body vertically on rings, parallettes, or bars with arms extended and body tight.",
    targetMuscleGroups: ["Shoulders", "Triceps", "Core", "Chest"],
    mistakes: ["Bent elbows", "Loose core", "Sagging hips"],
    progression: ["front-support", "elevated-vertical-support"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "high-knees",
    name: "High Knees",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "explosive",
    tags: ["cardio", "core", "lower-body", "bodyweight", "calorie-burn"],
    bodyRegion: "lower-body",
    description:
      "Run in place while driving knees up towards your chest as fast as possible, keeping core tight.",
    targetMuscleGroups: [
      "Quadriceps",
      "Hip Flexors",
      "Glutes",
      "Core",
      "Calves",
    ],
    mistakes: [
      "Leaning back",
      "Not lifting knees high",
      "Bouncing excessively",
    ],
    progression: ["marching-high-knees", "fast-high-knees-sprints"],
    unitPoint: 0.2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "jumping-lunges",
    name: "Jumping Lunges",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "explosive",
    tags: ["lower-body", "plyometric", "cardio", "glutes", "quads"],
    bodyRegion: "lower-body",
    description:
      "Alternate jumping lunges by switching legs mid-air, landing softly with knees at 90 degrees.",
    targetMuscleGroups: [
      "Quadriceps",
      "Glutes",
      "Hamstrings",
      "Calves",
      "Core",
    ],
    mistakes: [
      "Knee collapsing inward",
      "Uneven landing",
      "Not going deep enough",
    ],
    progression: ["static-lunge", "alternating-step-lunge", "jumping-lunges"],
    unitPoint: 0.8,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "split-squat",
    name: "Split Squat",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["lower-body", "quads", "glutes", "balance", "bodyweight"],
    bodyRegion: "lower-body",
    description:
      "Step one foot forward, lower back knee towards the ground while keeping chest up, then return to start.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    mistakes: [
      "Front knee collapsing inward",
      "Leaning forward",
      "Back knee touching the ground forcefully",
    ],
    progression: ["assisted-split-squat", "lunge", "jumping-lunge"],
    unitPoint: 0.75,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "pseudo-planche-pushup",
    name: "Pseudo Planche Push-up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: [
      "upper-body",
      "core",
      "chest",
      "shoulders",
      "bodyweight",
      "planche-progression",
    ],
    bodyRegion: "upper-body",
    description:
      "Lean forward while performing a push-up, hands near hips, keeping core tight and elbows tucked.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    mistakes: [
      "Hips sagging",
      "Elbows flaring",
      "Partial range",
      "Using momentum",
    ],
    progression: ["standard-pushup", "decline-pushup", "pseudo-planche-pushup"],
    unitPoint: 2.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "decline-pushup",
    name: "Decline Push-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["upper-body", "chest", "core", "bodyweight", "horizontal-push"],
    description:
      "Place your feet on an elevated surface and hands on the floor, lower your chest and push back up.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    bodyRegion: "upper-body",
    mistakes: [
      "Sagging hips",
      "Partial range",
      "Elbows flaring",
      "Head dropping",
    ],
    progression: ["incline-pushup", "standard-pushup", "decline-pushup"],
    unitPoint: 1.3,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "russian-twists",
    name: "Russian Twists",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["obliques", "core", "rotational", "abs", "bodyweight"],
    description:
      "Sit with knees bent, lean back slightly, rotate torso side to side, touching floor or hands each side.",
    targetMuscleGroups: ["Obliques", "Core", "Hip Flexors"],
    bodyRegion: "core",
    mistakes: [
      "Rounding back",
      "Using momentum",
      "Feet lifting off floor excessively",
    ],
    progression: ["seated-oblique-twist", "feet-elevated-russian-twist"],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "bicycle-crunches",
    name: "Bicycle Crunches",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "abs", "obliques", "dynamic", "bodyweight"],
    description:
      "Lie on your back, lift shoulders and legs, bring opposite elbow to knee while extending the other leg, alternate sides.",
    targetMuscleGroups: ["Core", "Obliques", "Hip Flexors"],
    bodyRegion: "core",
    mistakes: [
      "Pulling neck with hands",
      "Not fully extending leg",
      "Rushing movement",
    ],
    progression: ["slow-bicycle-crunch", "feet-on-ground-bicycle-crunch"],
    unitPoint: 0.6,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "v-ups",
    name: "V-Ups",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["abs", "core", "bodyweight", "dynamic", "anti-extension"],
    description:
      "Lie flat, lift legs and torso simultaneously to form a V-shape, reaching hands toward toes.",
    targetMuscleGroups: ["Core", "Hip Flexors", "Rectus Abdominis"],
    mistakes: ["Rounding back", "Using momentum", "Partial range"],
    bodyRegion: "core",
    progression: ["tuck-ups", "single-leg-v-ups"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "side-hip-dips",
    name: "Side Hip Dips",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["obliques", "core", "plank-variation", "bodyweight"],
    description:
      "From a side plank, lower hips toward the ground and lift back up slowly, keeping core tight.",
    targetMuscleGroups: ["Obliques", "Core", "Shoulders", "Glutes"],
    bodyRegion: "core",
    mistakes: [
      "Hips sagging",
      "Torso rotation",
      "Holding breath",
      "Neck alignment",
    ],
    progression: ["side-plank-hold", "side-hip-dip-knee-bent"],
    unitPoint: 0.6,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "tuck-lsit-hang",
    name: "Tuck L-Sit Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    bodyRegion: "core",
    tags: ["core", "shoulders", "arms", "bodyweight"],
    description:
      "Hang from a bar or rings, knees tucked to chest, keeping core tight and shoulders engaged.",
    targetMuscleGroups: ["Core", "Shoulders", "Triceps", "Hip Flexors"],
    mistakes: [
      "Shoulders shrugged",
      "Legs drooping",
      "Back rounding",
      "Holding breath",
    ],
    progression: ["tuck-lsit-hang", "one-leg-lsit-hang", "full-lsit-hang"],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "one-leg-lsit-hang",
    name: "One-Leg L-Sit Hang",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    bodyRegion: "core",
    tags: ["core", "shoulders", "arms", "bodyweight"],
    description:
      "Hang from a bar or rings with one leg straight and the other tucked, maintaining tight core and engaged shoulders.",
    targetMuscleGroups: [
      "Core",
      "Shoulders",
      "Triceps",
      "Hip Flexors",
      "Glutes",
    ],
    mistakes: [
      "Hips sagging",
      "Back arching",
      "Straight leg drooping",
      "Elbows bending",
    ],
    progression: ["tuck-lsit-hang", "one-leg-lsit-hang", "full-lsit-hang"],
    unitPoint: 0.75,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "full-lsit-hang",
    name: "Full L-Sit Hang",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    bodyRegion: "core",
    tags: ["core", "shoulders", "arms", "bodyweight", "advanced"],
    description:
      "Hang from a bar or rings with legs fully extended in front, body tight, shoulders engaged, and core braced.",
    targetMuscleGroups: [
      "Core",
      "Shoulders",
      "Triceps",
      "Hip Flexors",
      "Glutes",
    ],
    mistakes: [
      "Shoulders shrugged",
      "Back arching",
      "Legs dropping",
      "Breathing irregularly",
    ],
    progression: ["tuck-lsit-hang", "one-leg-lsit-hang", "full-lsit-hang"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "tuck-lsit-pullup",
    name: "Tuck L-Sit Pull-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    bodyRegion: "upper-body",
    tags: ["core", "back", "biceps", "bodyweight"],
    description:
      "Perform a pull-up while holding knees tucked to chest, keeping core tight and shoulders engaged.",
    targetMuscleGroups: ["Lats", "Biceps", "Core", "Shoulders", "Hip Flexors"],
    mistakes: [
      "Swinging torso",
      "Elbows flaring",
      "Knees dropping",
      "Partial range of motion",
    ],
    progression: ["tuck-lsit-hang", "tuck-lsit-pullup", "full-lsit-pullup"],
    unitPoint: 4,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "full-lsit-pullup",
    name: "Full L-Sit Pull-up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    bodyRegion: "upper-body",
    tags: ["core", "back", "biceps", "bodyweight", "advanced"],
    description:
      "Perform a pull-up while holding legs fully extended in front, keeping core tight, shoulders engaged, and elbows close to the body.",
    targetMuscleGroups: [
      "Lats",
      "Biceps",
      "Core",
      "Shoulders",
      "Hip Flexors",
      "Glutes",
    ],
    mistakes: [
      "Swinging legs",
      "Partial range of motion",
      "Elbows flaring",
      "Shoulders shrugging",
    ],
    progression: ["tuck-lsit-hang", "one-leg-lsit-hang", "full-lsit-pullup"],
    unitPoint: 6,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "handstand",
    name: "Handstand",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["shoulders", "core", "balance", "bodyweight", "inverted"],
    description:
      "Hold a straight-body handstand, either freestanding or against a wall, keeping the body tight and aligned.",
    targetMuscleGroups: [
      "Shoulders",
      "Core",
      "Triceps",
      "Upper Back",
      "Glutes",
    ],
    bodyRegion: "upper-body",
    mistakes: [
      "Arching back",
      "Bent elbows",
      "Looking down or forward",
      "Poor hand placement",
    ],
    progression: ["wall-supported-handstand", "handstand-kick-ups"],
    unitPoint: 0.7,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "wall-supported-handstand",
    name: "Wall Supported Handstand",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["shoulders", "core", "balance", "bodyweight", "inverted"],
    description:
      "Hold a handstand with your back or chest against the wall for support, focusing on alignment and shoulder engagement.",
    targetMuscleGroups: [
      "Shoulders",
      "Core",
      "Triceps",
      "Upper Back",
      "Glutes",
    ],
    bodyRegion: "upper-body",
    mistakes: [
      "Overarching back",
      "Bent elbows",
      "Feet too far from wall",
      "Neck misalignment",
    ],
    progression: ["handstand"],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "handstand-pushup",
    name: "Handstand Push-Up",
    level: "expert",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["shoulders", "triceps", "core", "bodyweight", "inverted"],
    description:
      "From a handstand position, lower your head to the ground and press back up, maintaining core tension and shoulder alignment.",
    targetMuscleGroups: ["Shoulders", "Triceps", "Core", "Upper Back"],
    bodyRegion: "upper-body",
    mistakes: [
      "Arching back",
      "Elbows flaring out",
      "Incomplete range of motion",
      "Head hitting the ground",
    ],
    progression: ["wall-supported-handstand", "handstand"],
    unitPoint: 2.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "planche",
    name: "Planche",
    level: "elite",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: [
      "shoulders",
      "core",
      "triceps",
      "bodyweight",
      "isometric",
      "inverted",
    ],
    description:
      "Hold your body parallel to the ground supported only by your hands, keeping arms straight and core tight.",
    targetMuscleGroups: ["Shoulders", "Core", "Triceps", "Chest", "Lower Back"],
    bodyRegion: "upper-body",
    mistakes: [
      "Hips sagging",
      "Bent elbows",
      "Arching back",
      "Neck misalignment",
    ],
    progression: ["pseudo-planch-lean", "tuck-planche"],
    unitPoint: 5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "pseudo-planche-lean",
    name: "Pseudo Planche Lean",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["shoulders", "core", "triceps", "bodyweight", "isometric"],
    description:
      "Lean forward with hands on the floor while keeping arms straight and body tight, engaging core and shoulders to mimic planche hold.",
    targetMuscleGroups: ["Shoulders", "Core", "Triceps", "Chest"],
    bodyRegion: "upper-body",
    mistakes: [
      "Bent elbows",
      "Hips too high or sagging",
      "Not leaning enough",
      "Neck misalignment",
    ],
    progression: ["planche", "tuck-planche"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "tuck-planche",
    name: "Tuck Planche",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["shoulders", "core", "triceps", "bodyweight", "isometric"],
    description:
      "Hold a planche with knees tucked to the chest, arms straight, and core tight, keeping the body parallel to the ground.",
    targetMuscleGroups: ["Shoulders", "Core", "Triceps", "Chest"],
    bodyRegion: "upper-body",
    mistakes: [
      "Hips sagging",
      "Bent elbows",
      "Arching back",
      "Not keeping knees tucked",
    ],
    progression: ["pseudo-planche-lean", "advanced-tuck-planche"],
    unitPoint: 1.8,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "one-leg-tuck-planche",
    name: "One-Leg Tuck Planche",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["shoulders", "core", "triceps", "bodyweight", "isometric"],
    description:
      "From a tuck planche, extend one leg forward while keeping the other leg tucked, arms straight and body parallel to the ground.",
    targetMuscleGroups: [
      "Shoulders",
      "Core",
      "Triceps",
      "Chest",
      "Hip Flexors",
    ],
    bodyRegion: "upper-body",
    mistakes: [
      "Hips sagging",
      "Bent elbows",
      "Arching back",
      "Not keeping tucked leg tight",
      "Uneven leg extension",
    ],
    progression: ["tuck-planche", "advanced-tuck-planche"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "advanced-tuck-planche",
    name: "Advanced Tuck Planche",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["shoulders", "core", "triceps", "bodyweight", "isometric"],
    description:
      "From a tuck planche, extend hips slightly to increase difficulty while keeping knees tucked, arms straight, and body parallel.",
    targetMuscleGroups: ["Shoulders", "Core", "Triceps", "Chest"],
    bodyRegion: "upper-body",
    mistakes: [
      "Hips sagging or too high",
      "Bent elbows",
      "Arching back",
      "Knees not tucked",
    ],
    progression: ["tuck-planche", "straddle-planche"],
    unitPoint: 2.2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "straddle-planche",
    name: "Straddle Planche",
    level: "expert",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["shoulders", "core", "triceps", "bodyweight", "isometric"],
    description:
      "Perform a planche with legs spread in a straddle position, arms straight, keeping the body parallel to the ground.",
    targetMuscleGroups: [
      "Shoulders",
      "Core",
      "Triceps",
      "Chest",
      "Hip Flexors",
    ],
    bodyRegion: "upper-body",
    mistakes: [
      "Hips sagging",
      "Bent elbows",
      "Arching back",
      "Legs not fully straddled",
    ],
    progression: ["advanced-tuck-planche", "full-planche"],
    unitPoint: 3,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "tuck-front-lever",
    name: "Tuck Front Lever",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["lats", "core", "shoulders", "bodyweight", "isometric"],
    description:
      "Hang from a pull-up bar and hold your body horizontal with knees tucked to the chest, arms straight and core tight.",
    targetMuscleGroups: ["Lats", "Core", "Shoulders", "Upper Back", "Glutes"],
    bodyRegion: "core",
    mistakes: [
      "Hips sagging",
      "Bent arms",
      "Arching back",
      "Shoulders not engaged",
    ],
    progression: ["advanced-tuck-front-lever"],
    unitPoint: 1.3,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "advanced-tuck-front-lever",
    name: "Advanced Tuck Front Lever",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["lats", "core", "shoulders", "bodyweight", "isometric"],
    description:
      "From a tuck front lever, extend hips slightly while keeping knees tucked, maintaining a straight arm hold and engaged core.",
    targetMuscleGroups: ["Lats", "Core", "Shoulders", "Upper Back", "Glutes"],
    bodyRegion: "core",
    mistakes: ["Hips sagging", "Bent arms", "Arching back", "Knees not tucked"],
    progression: ["one-leg-front-lever"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "one-leg-front-lever",
    name: "One-Leg Front Lever",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["lats", "core", "shoulders", "bodyweight", "isometric"],
    description:
      "From a tuck or advanced tuck front lever, extend one leg while keeping the other tucked, arms straight and body horizontal.",
    targetMuscleGroups: ["Lats", "Core", "Shoulders", "Upper Back", "Glutes"],
    bodyRegion: "core",
    mistakes: [
      "Hips sagging",
      "Bent arms",
      "Arching back",
      "Uneven leg extension",
    ],
    progression: ["straddle-front-lever"],
    unitPoint: 2.2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "straddle-front-lever",
    name: "Straddle Front Lever",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["lats", "core", "shoulders", "bodyweight", "isometric"],
    description:
      "Perform a front lever with legs spread in a straddle position, keeping arms straight and body horizontal.",
    targetMuscleGroups: [
      "Lats",
      "Core",
      "Shoulders",
      "Upper Back",
      "Glutes",
      "Hip Flexors",
    ],
    bodyRegion: "core",
    mistakes: [
      "Hips sagging",
      "Bent arms",
      "Arching back",
      "Legs not fully straddled",
    ],
    progression: ["full-front-lever"],
    unitPoint: 2.8,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "full-front-lever",
    name: "Full Front Lever",
    level: "expert",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["lats", "core", "shoulders", "bodyweight", "isometric"],
    description:
      "Hang from a bar and hold your body fully horizontal with legs extended, arms straight, core engaged, and body parallel to the ground.",
    targetMuscleGroups: [
      "Lats",
      "Core",
      "Shoulders",
      "Upper Back",
      "Glutes",
      "Hip Flexors",
    ],
    bodyRegion: "core",
    mistakes: [
      "Hips sagging",
      "Bent arms",
      "Arching back",
      "Legs not fully extended",
    ],
    progression: [],
    unitPoint: 4,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "one-arm-pullup",
    name: "One-Arm Pull-Up",
    level: "elite",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["lats", "biceps", "forearms", "core", "bodyweight"],
    description:
      "Perform a pull-up using only one arm, keeping the body straight and controlled throughout the movement.",
    targetMuscleGroups: ["Lats", "Biceps", "Forearms", "Core", "Shoulders"],
    bodyRegion: "upper-body",
    mistakes: [
      "Swinging body",
      "Bent elbow",
      "Partial range of motion",
      "Poor grip",
    ],
    progression: ["pullup", "tuck-front-lever-pullup"],
    unitPoint: 10,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "tuck-front-lever-pullup",
    name: "Tuck Front Lever Pull-Up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "isometric",
    tags: ["lats", "core", "biceps", "shoulders", "bodyweight"],
    description:
      "From a tuck front lever hang, perform a pull-up while keeping the body horizontal with knees tucked, engaging core and upper back.",
    targetMuscleGroups: ["Lats", "Core", "Biceps", "Shoulders", "Upper Back"],
    bodyRegion: "core",
    mistakes: [
      "Hips sagging",
      "Bent elbows",
      "Swinging body",
      "Knees not tucked",
    ],
    progression: ["tuck-front-lever", "one-arm-pullup"],
    unitPoint: 4.5,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "knee-pushups",
    name: "Knee Push-ups",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["chest", "triceps", "shoulders", "bodyweight"],
    description:
      "Perform push-ups on your knees to reduce load while engaging chest, shoulders, and triceps.",
    targetMuscleGroups: ["Chest", "Triceps", "Shoulders", "Core"],
    bodyRegion: "upper-body",
    mistakes: [
      "Hips sagging",
      "Elbows flaring out",
      "Incomplete range of motion",
    ],
    progression: ["pushups"],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "inverted-rows",
    name: "Inverted Rows",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["back", "biceps", "core", "bodyweight"],
    description:
      "Pull your chest toward a bar while keeping your body straight, targeting upper back and biceps.",
    targetMuscleGroups: ["Back", "Biceps", "Forearms", "Core"],
    bodyRegion: "upper-body",
    mistakes: ["Hips sagging", "Incomplete pull", "Neck strain"],
    progression: ["bodyweight-rows", "pullups"],
    unitPoint: 0.8,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "wall-sit",
    name: "Wall Sit",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["quads", "glutes", "hamstrings", "isometric"],
    description:
      "Sit against a wall with knees at 90 degrees and hold the position to strengthen legs.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Calves"],
    bodyRegion: "lower-body",
    mistakes: ["Hips too high or low", "Knees past toes", "Arching back"],
    progression: ["wall-sit-hold-longer", "chair-squat"],
    unitPoint: 0.25,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "jumping-jacks",
    name: "Jumping Jacks",
    level: "beginner",
    measurement: "reps",
    type: "cardio",
    movementPattern: "full-body",
    tags: ["cardio", "legs", "shoulders", "bodyweight"],
    description:
      "Jump while raising arms overhead and spreading legs, then return to starting position.",
    targetMuscleGroups: ["Legs", "Shoulders", "Core"],
    bodyRegion: "full-body",
    mistakes: ["Poor landing form", "Not fully extending arms or legs"],
    progression: ["jumping-jacks-faster", "star-jumps"],
    unitPoint: 0.1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "reverse-crunches",
    name: "Reverse Crunches",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["abs", "core", "lower-abs", "bodyweight"],
    description:
      "Lift your hips toward your chest while lying on your back, engaging the lower abs.",
    targetMuscleGroups: ["Lower Abs", "Obliques", "Core"],
    bodyRegion: "core",
    mistakes: ["Using momentum", "Arching back", "Neck strain"],
    progression: ["leg-raises", "reverse-crunch-hold"],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "calf-raises",
    name: "Calf Raises",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["calves", "legs", "bodyweight"],
    description:
      "Raise your heels off the ground while standing to strengthen the calves.",
    targetMuscleGroups: ["Calves", "Ankles"],
    bodyRegion: "lower-body",
    mistakes: ["Bouncing", "Incomplete range of motion", "Leaning forward"],
    progression: ["single-leg-calf-raises"],
    unitPoint: 0.2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "seated-knee-tucks",
    name: "Seated Knee Tucks",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["abs", "hip-flexors", "core", "bodyweight"],
    description:
      "Sit on the edge of a bench or chair, tuck knees toward chest and extend back slowly.",
    targetMuscleGroups: ["Core", "Hip Flexors", "Lower Abs"],
    bodyRegion: "core",
    mistakes: ["Swinging legs", "Leaning back too much", "Using momentum"],
    progression: ["hanging-knee-raises"],
    unitPoint: 0.4,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "crunches",
    name: "Crunches",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["abs", "core", "upper-abs", "bodyweight"],
    description:
      "Lie on your back with knees bent, lift your upper body toward your knees, engaging abs.",
    targetMuscleGroups: ["Upper Abs", "Core"],
    bodyRegion: "core",
    mistakes: ["Pulling neck", "Using momentum", "Incomplete contraction"],
    progression: ["sit-ups", "weighted-crunches"],
    unitPoint: 0.4,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "scapular-pullups",
    name: "Scapular Pull-ups",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["lats", "shoulders", "scapula", "bodyweight"],
    description:
      "Hang from a bar and pull your shoulder blades down and together without bending elbows.",
    targetMuscleGroups: ["Lats", "Traps", "Shoulders", "Scapular Stabilizers"],
    bodyRegion: "upper-body",
    mistakes: ["Bending elbows", "Shrugging shoulders", "Swinging body"],
    progression: ["pullups"],
    unitPoint: 0.8,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "scapular-pushups",
    name: "Scapular Push-ups",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["chest", "shoulders", "scapula", "bodyweight"],
    description:
      "Perform push-ups while keeping arms straight and only moving the shoulder blades together and apart.",
    targetMuscleGroups: ["Chest", "Shoulders", "Traps", "Core"],
    bodyRegion: "upper-body",
    mistakes: ["Bending elbows", "Sagging hips", "Using momentum"],
    progression: ["pushups"],
    unitPoint: 0.5,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "flutter-kicks",
    name: "Flutter Kicks",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["abs", "lower-abs", "core", "bodyweight", "legs"],
    description:
      "Lie on your back, lift legs slightly off the ground and kick alternately while keeping core tight.",
    targetMuscleGroups: ["Lower Abs", "Hip Flexors", "Core", "Legs"],
    bodyRegion: "core",
    mistakes: ["Arching back", "Bouncing legs", "Neck strain"],
    progression: ["scissor-kicks"],
    unitPoint: 0.3,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "bench-dips",
    name: "Bench Dips",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["triceps", "chest", "shoulders", "bodyweight"],
    description:
      "Place hands on a bench behind you, lower your body and push back up using triceps.",
    targetMuscleGroups: ["Triceps", "Chest", "Shoulders"],
    bodyRegion: "upper-body",
    mistakes: [
      "Elbows flaring out",
      "Shoulders shrugging",
      "Incomplete range of motion",
    ],
    progression: ["dips"],
    unitPoint: 0.7,
    dateCreated: new Date().toISOString(),
  },
];
