import { Exercise } from "./types";
export const exercises: Exercise[] = [
  {
    id: "plank",
    name: "Plank",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "isometric", "anti-extension", "spine-stability"],
    description:
      "Maintain a straight line from head to heels while keeping your core tight and hips level.",
    targetMuscleGroups: ["Core", "Shoulders", "Glutes"],
    bodyRegion: "core",
    mistakes: [
      "Sagging hips",
      "Piking hips too high",
      "Holding breath",
      "Neck not aligned with spine",
    ],
    progression: [], // beginner already
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "side-plank",
    name: "Side Plank",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["obliques", "isometric", "core-stability"],
    description:
      "Lie on your side, lift hips off the ground, maintain a straight line from head to feet, supporting on one arm.",
    targetMuscleGroups: ["Obliques", "Core", "Shoulders", "Glutes"],
    bodyRegion: "core",
    mistakes: ["Hips sagging", "Rotating torso", "Neck misalignment"],
    progression: [], // beginner already
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "isometric", "abs", "bodyweight"],
    description:
      "Lie on your back, lift arms and legs off the floor, creating a hollow shape with your body while keeping lower back pressed down.",
    targetMuscleGroups: ["Core", "Hip Flexors"],
    bodyRegion: "core",
    mistakes: ["Arching lower back", "Neck tension", "Legs too low or high"],
    progression: ["dead-bug"], // easier version
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    level: "beginner",
    measurement: "reps",
    type: "conditioning",
    movementPattern: "core",
    tags: ["core", "cardio", "dynamic", "bodyweight"],
    description:
      "From a push-up position, alternate driving knees toward your chest quickly while keeping your back straight.",
    targetMuscleGroups: ["Core", "Shoulders", "Legs", "Hip Flexors"],
    bodyRegion: "full-body",
    mistakes: ["Hips sagging or piking", "Not engaging core", "Bouncing hands"],
    progression: [], // beginner-friendly
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "leg-raises",
    name: "Leg Raises",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["lower-abs", "bodyweight", "core"],
    description:
      "Lie on your back, lift legs toward the ceiling while keeping lower back pressed to the floor, then slowly lower.",
    targetMuscleGroups: ["Lower Abs", "Hip Flexors", "Core"],
    bodyRegion: "core",
    mistakes: [
      "Arching lower back",
      "Swinging legs",
      "Not controlling descent",
    ],
    progression: ["bent-knee-leg-raises"], // easier
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "burpees",
    name: "Burpees",
    level: "intermediate",
    measurement: "reps",
    type: "conditioning",
    movementPattern: "full-body",
    tags: ["explosive", "cardio", "bodyweight", "full-body"],
    bodyRegion: "full-body",
    description:
      "From standing, drop into a squat, kick feet back into a push-up, return to squat, then jump up explosively.",
    targetMuscleGroups: ["Legs", "Core", "Chest", "Shoulders", "Arms"],
    mistakes: [
      "Not going full range",
      "Poor landing mechanics",
      "Sagging hips during plank portion",
    ],
    progression: ["squat-thrusts"], // easier version
    unitPoint: 3,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "jump-squats",
    name: "Jump Squats",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["explosive", "legs", "plyometric", "bodyweight"],
    description:
      "Perform a squat and explode upwards into a jump, landing softly and returning to squat position.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Calves"],
    bodyRegion: "lower-body",
    mistakes: [
      "Knees collapsing inward",
      "Landing stiffly",
      "Shallow squat depth",
    ],
    progression: ["air-squat"], // easier version
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "pullup",
    name: "Pull-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["upper-body", "back", "arms", "bodyweight", "vertical-pull"],
    description:
      "From a dead hang, pull your chin over the bar using an overhand grip, keeping core tight.",
    targetMuscleGroups: ["Back", "Biceps", "Shoulders", "Core"],
    bodyRegion: "upper-body",
    mistakes: ["Kipping/momentum", "Partial range", "Shrugging shoulders"],
    progression: ["assisted-pull-up", "band-assisted-pull-up"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "chin-up",
    name: "Chin-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["upper-body", "back", "biceps", "bodyweight", "vertical-pull"],
    bodyRegion: "upper-body",
    description:
      "From a dead hang, pull your chin over the bar using an underhand grip, keeping core tight.",
    targetMuscleGroups: ["Biceps", "Back", "Shoulders", "Core"],
    mistakes: ["Elbow flaring", "Jerky motion", "Partial range"],
    progression: ["negative-chin-up", "assisted-chin-up"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "pushup",
    name: "Push-up",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["bodyweight", "upper-body", "horizontal-push", "core-stability"],
    bodyRegion: "upper-body",
    description:
      "Keep your core tight, body in a straight line, and elbows at about a 45-degree angle as you lower and push up.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    mistakes: [
      "Sagging hips",
      "Flared elbows",
      "Partial range of motion",
      "Head dropping or neck craned forward",
    ],
    progression: ["knee-push-up", "incline-push-up", "diamond-push-up"], // easier → standard → harder variations
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "squat",
    name: "Squat",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["bodyweight", "lower-body", "knee-dominant", "mobility"],
    bodyRegion: "lower-body",
    description:
      "Keep your chest up and back neutral as you lower your hips until your thighs are parallel to the ground.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    mistakes: [
      "Knees collapsing inward",
      "Heels lifting off the ground",
      "Rounded lower back",
      "Shallow depth",
    ],
    progression: ["assisted-wall-squat", "box-squat"], // easier variations
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "deadhang",
    name: "Dead Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["grip", "shoulder-health", "scapular-control", "isometric"],
    bodyRegion: "upper-body",
    description:
      "Hang from the bar with straight arms, relaxed shoulders, and controlled breathing.",
    targetMuscleGroups: ["Forearms", "Grip", "Shoulders"],
    mistakes: [
      "Shrugging shoulders excessively",
      "Bending the arms",
      "Holding breath",
      "Losing grip due to poor hand placement",
    ],
    progression: ["scapular-hang"], // easier scapular-focused hang before full dead hang
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "plank",
    name: "Plank",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "isometric", "anti-extension", "spine-stability"],
    bodyRegion: "core",
    description:
      "Maintain a straight line from head to heels while keeping your core tight and hips level.",
    targetMuscleGroups: ["Core", "Shoulders", "Glutes"],
    mistakes: [
      "Sagging hips",
      "Piking hips too high",
      "Holding breath",
      "Neck not aligned with spine",
    ],
    progression: ["knee-plank", "elbow-plank", "side-plank"], // easier → standard → advanced variations
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "horse-stance",
    name: "Horse Stance",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "legs",
    tags: ["isometric", "lower-body", "stance", "mobility"],
    bodyRegion: "lower-body",
    description:
      "Stand with feet wider than shoulders, knees bent, hips low, and back straight. Hold the position.",
    targetMuscleGroups: [
      "Quadriceps",
      "Glutes",
      "Hamstrings",
      "Adductors",
      "Core",
    ],
    mistakes: [
      "Knees collapsing inward",
      "Back rounding",
      "Feet too close together",
      "Leaning forward",
    ],
    progression: ["wall-squat", "deeper-horse-stance", "weighted-horse-stance"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "one-arm-pushup",
    name: "One-Arm Push-up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: [
      "bodyweight",
      "upper-body",
      "horizontal-push",
      "core-stability",
      "strength",
    ],
    description:
      "Perform a push-up using one arm while keeping your body aligned. The other arm may rest on your back or side for balance.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    bodyRegion: "upper-body",
    mistakes: [
      "Hip sagging",
      "Rotating torso excessively",
      "Partial range of motion",
      "Elbow flaring",
    ],
    progression: ["archer-pushup", "uneven-pushup", "assisted-one-arm-pushup"],
    unitPoint: 3,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "archer-pushup",
    name: "Archer Push-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: [
      "bodyweight",
      "upper-body",
      "horizontal-push",
      "core-stability",
      "strength",
    ],
    description:
      "Perform a push-up while extending one arm straight to the side, shifting most weight to the other arm.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    bodyRegion: "upper-body",
    mistakes: [
      "Sagging hips",
      "Elbow flaring",
      "Partial range",
      "Rotating torso",
    ],
    progression: ["standard-pushup", "incline-archer-pushup", "one-arm-pushup"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "diamond-pushup",
    name: "Diamond Push-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["bodyweight", "upper-body", "horizontal-push", "triceps-focus"],
    bodyRegion: "upper-body",
    description:
      "Place your hands close together under your chest forming a diamond shape with thumbs and index fingers. Lower and push up keeping elbows close.",
    targetMuscleGroups: ["Triceps", "Chest", "Shoulders", "Core"],
    mistakes: [
      "Elbow flaring",
      "Sagging hips",
      "Partial range",
      "Head dropping",
    ],
    progression: ["standard-pushup", "close-grip-pushup", "archer-pushup"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "human-flag",
    name: "Human Flag",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "obliques", "bodyweight", "flag", "advanced-skill"],
    bodyRegion: "full-body",
    description:
      "Grip a vertical pole and hold your body horizontally, parallel to the ground, using obliques, lats, and core.",
    targetMuscleGroups: ["Obliques", "Lats", "Shoulders", "Core", "Forearms"],
    mistakes: ["Sagging legs", "Bent arms", "Arching back", "Grip failure"],
    progression: [
      "vertical-pole-hang",
      "tuck-human-flag",
      "straddle-human-flag",
    ],
    unitPoint: 4,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "bodyweight", "isometric", "anti-extension", "abs"],
    bodyRegion: "core",
    description:
      "Lie on your back, lift your legs and shoulders slightly off the ground, keep lower back pressed into the floor, arms extended overhead.",
    targetMuscleGroups: ["Core", "Hip Flexors", "Shoulders"],
    mistakes: ["Arching lower back", "Raising legs too high", "Neck tension"],
    progression: ["tuck-hollow-hold", "single-leg-hollow-hold"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "mountain-climbers",
    name: "Mountain Climbers",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "explosive",
    tags: ["core", "cardio", "bodyweight", "full-body"],
    bodyRegion: "full-body",
    description:
      "From a plank position, alternate driving knees toward your chest at a quick pace while keeping core tight.",
    targetMuscleGroups: [
      "Core",
      "Shoulders",
      "Hip Flexors",
      "Chest",
      "Triceps",
    ],
    mistakes: [
      "Hips too high or low",
      "Bouncing excessively",
      "Poor arm alignment",
    ],
    progression: ["slow-mountain-climbers", "high-knees-mountain-climbers"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "muscle-up",
    name: "Muscle-up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    tags: ["upper-body", "bodyweight", "pull", "explosive", "bar"],
    bodyRegion: "upper-body",
    description:
      "Pull up explosively over a bar and transition into a dip position at the top.",
    targetMuscleGroups: [
      "Back",
      "Biceps",
      "Chest",
      "Shoulders",
      "Triceps",
      "Core",
    ],
    mistakes: [
      "Kipping excessively",
      "Partial range of motion",
      "Elbows flaring",
      "Lack of control on descent",
    ],
    progression: ["pull-up", "chest-to-bar pull-up", "explosive pull-up"],
    unitPoint: 4,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "sissy-squat",
    name: "Sissy Squat",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["quadriceps", "bodyweight", "knee-dominant"],
    bodyRegion: "lower-body",
    description:
      "Lean back while keeping hips extended and knees forward, lowering your body, and then return upright.",
    targetMuscleGroups: ["Quadriceps", "Core"],
    mistakes: [
      "Leaning too far back",
      "Knees collapsing",
      "Arching lower back",
    ],
    progression: ["assisted-sissy-squat", "wall-squat"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "pistol-squat",
    name: "Pistol Squat",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["bodyweight", "single-leg", "mobility", "strength"],
    description:
      "Squat on one leg while the other leg is extended in front, lowering until the thigh is parallel to the floor.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    bodyRegion: "lower-body",
    mistakes: [
      "Knee valgus",
      "Leaning forward",
      "Rounding back",
      "Loss of balance",
    ],
    progression: [
      "assisted-pistol-squat",
      "box-pistol-squat",
      "partial-range-pistol",
    ],
    unitPoint: 3,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "knee-raise",
    name: "Knee Raise",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["abs", "bodyweight", "pull", "hanging"],
    bodyRegion: "core",
    description:
      "Hang from a bar and lift knees toward your chest using your core muscles.",
    targetMuscleGroups: ["Lower Abs", "Hip Flexors", "Grip", "Forearms"],
    mistakes: ["Swinging body", "Not controlling legs", "Arching back"],
    progression: ["tuck-knee-raise", "single-leg-knee-raise"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "elevated-pike-hold",
    name: "Elevated Pike Hold",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "bodyweight", "isometric", "shoulder-stability"],
    bodyRegion: "core",
    description:
      "Place feet on an elevated surface and hands on the floor, forming an inverted 'V'. Hold the position while keeping shoulders and core tight.",
    targetMuscleGroups: ["Shoulders", "Core", "Glutes", "Hamstrings"],
    mistakes: ["Sagging hips", "Bent arms", "Rounded back"],
    progression: [
      "regular-pike-hold",
      "elevated-pike-hold",
      "pike-to-handstand-progressions",
    ],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "incline-pushup",
    name: "Incline Push-up",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["upper-body", "bodyweight", "horizontal-push", "beginner-friendly"],
    bodyRegion: "upper-body",
    description:
      "Hands on an elevated surface, perform a push-up while keeping core tight and elbows at 45 degrees.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    mistakes: ["Sagging hips", "Partial range", "Flared elbows"],
    progression: ["wall-pushup", "incline-pushup", "standard-pushup"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "dips",
    name: "Dips",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: [
      "upper-body",
      "bodyweight",
      "vertical-push",
      "triceps-focus",
      "chest",
    ],
    bodyRegion: "upper-body",
    description:
      "Lower your body between parallel bars until shoulders are below elbows, then push back up.",
    targetMuscleGroups: ["Triceps", "Chest", "Shoulders", "Core"],
    mistakes: [
      "Elbows flaring",
      "Swinging body",
      "Partial range",
      "Leaning too far forward",
    ],
    progression: ["bench-dip", "assisted-dip", "full-dip"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "rope-skip",
    name: "Rope Skip",
    level: "beginner",
    measurement: "reps",
    type: "cardio",
    movementPattern: "explosive",
    tags: ["full-body", "cardio", "plyometric", "coordination"],
    bodyRegion: "full-body",
    description:
      "Jump over a rope continuously, landing softly on your feet and maintaining rhythm.",
    targetMuscleGroups: [
      "Calves",
      "Quads",
      "Glutes",
      "Shoulders",
      "Forearms",
      "Core",
    ],
    mistakes: ["Bouncing excessively", "Poor timing", "Rounding shoulders"],
    progression: [
      "low-speed-rope-skip",
      "alternating-feet-skip",
      "double-unders",
    ],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "dead-hang",
    name: "Dead Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["grip", "shoulder-health", "scapular-control", "isometric"],
    bodyRegion: "upper-body",
    description:
      "Hang from a bar with straight arms, relaxed shoulders, and controlled breathing.",
    targetMuscleGroups: ["Forearms", "Grip", "Shoulders"],
    mistakes: [
      "Shrugging shoulders",
      "Bending arms",
      "Holding breath",
      "Poor grip",
    ],
    progression: ["scapular-hang"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "active-hang",
    name: "Active Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["grip", "shoulder-health", "scapular-control", "bodyweight"],
    bodyRegion: "upper-body",
    description:
      "Hang from a bar while engaging the shoulders (pulling them down and back) and keeping core tight.",
    targetMuscleGroups: ["Shoulders", "Lats", "Forearms", "Core"],
    mistakes: ["Shrugging shoulders", "Bent elbows", "Loose core"],
    progression: ["scapular-hang", "dead-hang"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "passive-hang",
    name: "Passive Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["grip", "shoulder-relaxation", "bodyweight"],
    bodyRegion: "upper-body",
    description:
      "Hang from a bar with relaxed shoulders and arms fully extended, allowing the body to hang freely.",
    targetMuscleGroups: ["Forearms", "Shoulders", "Grip"],
    mistakes: ["Tensing shoulders", "Bent arms", "Swinging"],
    progression: ["dead-hang", "active-hang"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "front-support",
    name: "Front Support",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "shoulders", "triceps", "support-hold"],
    bodyRegion: "upper-body",
    description:
      "Hold yourself on parallel bars or floor in a straight-arm position with tight core and neutral spine.",
    targetMuscleGroups: ["Core", "Shoulders", "Triceps", "Chest"],
    mistakes: ["Sagging hips", "Bent elbows", "Rounded shoulders"],
    progression: ["knee-front-support", "elevated-front-support"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "side-support",
    name: "Side Support",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "obliques", "support-hold"],
    bodyRegion: "upper-body",
    description:
      "Hold yourself on one hand or elbow in a straight-arm side support position, keeping hips lifted.",
    targetMuscleGroups: ["Obliques", "Shoulders", "Core", "Glutes"],
    mistakes: ["Hips sagging", "Twisting torso", "Bent arm"],
    progression: ["knee-side-support", "elevated-side-support"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "back-support",
    name: "Back Support",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "posterior-chain", "support-hold"],
    bodyRegion: "upper-body",
    description:
      "Hold your body on hands and feet facing up, keeping shoulders, glutes, and core engaged.",
    targetMuscleGroups: ["Back", "Glutes", "Shoulders", "Core"],
    mistakes: ["Sagging hips", "Loose core", "Rounded shoulders"],
    progression: ["knee-back-support", "elevated-back-support"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "vertical-support",
    name: "Vertical Support",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    tags: ["core", "shoulders", "arms", "support-hold"],
    bodyRegion: "upper-body",
    description:
      "Support your body vertically on rings, parallettes, or bars with arms extended and body tight.",
    targetMuscleGroups: ["Shoulders", "Triceps", "Core", "Chest"],
    mistakes: ["Bent elbows", "Loose core", "Sagging hips"],
    progression: ["front-support", "elevated-vertical-support"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "high-knees",
    name: "High Knees",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "explosive",
    tags: ["cardio", "core", "lower-body", "bodyweight", "calorie-burn"],
    bodyRegion: "lower-body",
    description:
      "Run in place while driving knees up towards your chest as fast as possible, keeping core tight.",
    targetMuscleGroups: [
      "Quadriceps",
      "Hip Flexors",
      "Glutes",
      "Core",
      "Calves",
    ],
    mistakes: [
      "Leaning back",
      "Not lifting knees high",
      "Bouncing excessively",
    ],
    progression: ["marching-high-knees", "fast-high-knees-sprints"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "jumping-lunges",
    name: "Jumping Lunges",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "explosive",
    tags: ["lower-body", "plyometric", "cardio", "glutes", "quads"],
    bodyRegion: "lower-body",
    description:
      "Alternate jumping lunges by switching legs mid-air, landing softly with knees at 90 degrees.",
    targetMuscleGroups: [
      "Quadriceps",
      "Glutes",
      "Hamstrings",
      "Calves",
      "Core",
    ],
    mistakes: [
      "Knee collapsing inward",
      "Uneven landing",
      "Not going deep enough",
    ],
    progression: ["static-lunge", "alternating-step-lunge", "jumping-lunges"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "split-squat",
    name: "Split Squat",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "legs",
    tags: ["lower-body", "quads", "glutes", "balance", "bodyweight"],
    bodyRegion: "lower-body",
    description:
      "Step one foot forward, lower back knee towards the ground while keeping chest up, then return to start.",
    targetMuscleGroups: ["Quadriceps", "Glutes", "Hamstrings", "Core"],
    mistakes: [
      "Front knee collapsing inward",
      "Leaning forward",
      "Back knee touching the ground forcefully",
    ],
    progression: ["assisted-split-squat", "lunge", "jumping-lunge"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "pseudo-planche-pushup",
    name: "Pseudo Planche Push-up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: [
      "upper-body",
      "core",
      "chest",
      "shoulders",
      "bodyweight",
      "planche-progression",
    ],
    bodyRegion: "upper-body",
    description:
      "Lean forward while performing a push-up, hands near hips, keeping core tight and elbows tucked.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    mistakes: [
      "Hips sagging",
      "Elbows flaring",
      "Partial range",
      "Using momentum",
    ],
    progression: ["standard-pushup", "decline-pushup", "pseudo-planche-pushup"],
    unitPoint: 3,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "decline-pushup",
    name: "Decline Push-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "push",
    tags: ["upper-body", "chest", "core", "bodyweight", "horizontal-push"],
    description:
      "Place your feet on an elevated surface and hands on the floor, lower your chest and push back up.",
    targetMuscleGroups: ["Chest", "Shoulders", "Triceps", "Core"],
    bodyRegion: "upper-body",
    mistakes: [
      "Sagging hips",
      "Partial range",
      "Elbows flaring",
      "Head dropping",
    ],
    progression: ["incline-pushup", "standard-pushup", "decline-pushup"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "russian-twists",
    name: "Russian Twists",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["obliques", "core", "rotational", "abs", "bodyweight"],
    description:
      "Sit with knees bent, lean back slightly, rotate torso side to side, touching floor or hands each side.",
    targetMuscleGroups: ["Obliques", "Core", "Hip Flexors"],
    bodyRegion: "core",
    mistakes: [
      "Rounding back",
      "Using momentum",
      "Feet lifting off floor excessively",
    ],
    progression: ["seated-oblique-twist", "feet-elevated-russian-twist"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "bicycle-crunches",
    name: "Bicycle Crunches",
    level: "beginner",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["core", "abs", "obliques", "dynamic", "bodyweight"],
    description:
      "Lie on your back, lift shoulders and legs, bring opposite elbow to knee while extending the other leg, alternate sides.",
    targetMuscleGroups: ["Core", "Obliques", "Hip Flexors"],
    bodyRegion: "core",
    mistakes: [
      "Pulling neck with hands",
      "Not fully extending leg",
      "Rushing movement",
    ],
    progression: ["slow-bicycle-crunch", "feet-on-ground-bicycle-crunch"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "v-ups",
    name: "V-Ups",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["abs", "core", "bodyweight", "dynamic", "anti-extension"],
    description:
      "Lie flat, lift legs and torso simultaneously to form a V-shape, reaching hands toward toes.",
    targetMuscleGroups: ["Core", "Hip Flexors", "Rectus Abdominis"],
    mistakes: ["Rounding back", "Using momentum", "Partial range"],
    bodyRegion: "core",
    progression: ["tuck-ups", "single-leg-v-ups"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "side-hip-dips",
    name: "Side Hip Dips",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "core",
    tags: ["obliques", "core", "plank-variation", "bodyweight"],
    description:
      "From a side plank, lower hips toward the ground and lift back up slowly, keeping core tight.",
    targetMuscleGroups: ["Obliques", "Core", "Shoulders", "Glutes"],
    bodyRegion: "core",
    mistakes: [
      "Hips sagging",
      "Torso rotation",
      "Holding breath",
      "Neck alignment",
    ],
    progression: ["side-plank-hold", "side-hip-dip-knee-bent"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },

  {
    id: "tuck-lsit-hang",
    name: "Tuck L-Sit Hang",
    level: "beginner",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    bodyRegion: "core",
    tags: ["core", "shoulders", "arms", "bodyweight"],
    description:
      "Hang from a bar or rings, knees tucked to chest, keeping core tight and shoulders engaged.",
    targetMuscleGroups: ["Core", "Shoulders", "Triceps", "Hip Flexors"],
    mistakes: [
      "Shoulders shrugged",
      "Legs drooping",
      "Back rounding",
      "Holding breath",
    ],
    progression: ["tuck-lsit-hang", "one-leg-lsit-hang", "full-lsit-hang"],
    unitPoint: 1,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "one-leg-lsit-hang",
    name: "One-Leg L-Sit Hang",
    level: "intermediate",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    bodyRegion: "core",
    tags: ["core", "shoulders", "arms", "bodyweight"],
    description:
      "Hang from a bar or rings with one leg straight and the other tucked, maintaining tight core and engaged shoulders.",
    targetMuscleGroups: [
      "Core",
      "Shoulders",
      "Triceps",
      "Hip Flexors",
      "Glutes",
    ],
    mistakes: [
      "Hips sagging",
      "Back arching",
      "Straight leg drooping",
      "Elbows bending",
    ],
    progression: ["tuck-lsit-hang", "one-leg-lsit-hang", "full-lsit-hang"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "full-lsit-hang",
    name: "Full L-Sit Hang",
    level: "advanced",
    measurement: "seconds",
    type: "strength",
    movementPattern: "isometric",
    bodyRegion: "core",
    tags: ["core", "shoulders", "arms", "bodyweight", "advanced"],
    description:
      "Hang from a bar or rings with legs fully extended in front, body tight, shoulders engaged, and core braced.",
    targetMuscleGroups: [
      "Core",
      "Shoulders",
      "Triceps",
      "Hip Flexors",
      "Glutes",
    ],
    mistakes: [
      "Shoulders shrugged",
      "Back arching",
      "Legs dropping",
      "Breathing irregularly",
    ],
    progression: ["tuck-lsit-hang", "one-leg-lsit-hang", "full-lsit-hang"],
    unitPoint: 3,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "tuck-lsit-pullup",
    name: "Tuck L-Sit Pull-up",
    level: "intermediate",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    bodyRegion: "upper-body",
    tags: ["core", "back", "biceps", "bodyweight"],
    description:
      "Perform a pull-up while holding knees tucked to chest, keeping core tight and shoulders engaged.",
    targetMuscleGroups: ["Lats", "Biceps", "Core", "Shoulders", "Hip Flexors"],
    mistakes: [
      "Swinging torso",
      "Elbows flaring",
      "Knees dropping",
      "Partial range of motion",
    ],
    progression: ["tuck-lsit-hang", "tuck-lsit-pullup", "full-lsit-pullup"],
    unitPoint: 2,
    dateCreated: new Date().toISOString(),
  },
  {
    id: "full-lsit-pullup",
    name: "Full L-Sit Pull-up",
    level: "advanced",
    measurement: "reps",
    type: "strength",
    movementPattern: "pull",
    bodyRegion: "upper-body",
    tags: ["core", "back", "biceps", "bodyweight", "advanced"],
    description:
      "Perform a pull-up while holding legs fully extended in front, keeping core tight, shoulders engaged, and elbows close to the body.",
    targetMuscleGroups: [
      "Lats",
      "Biceps",
      "Core",
      "Shoulders",
      "Hip Flexors",
      "Glutes",
    ],
    mistakes: [
      "Swinging legs",
      "Partial range of motion",
      "Elbows flaring",
      "Shoulders shrugging",
    ],
    progression: ["tuck-lsit-hang", "one-leg-lsit-hang", "full-lsit-pullup"],
    unitPoint: 4,
    dateCreated: new Date().toISOString(),
  },
];
