export const quotes = [
  "You don't rush progress — you respect it.",
  "The floor is your gym.",
  "Your body is the weight.",
  "Master your body before adding weight.",
  "Anywhere is a gym if your mindset is right.",
  "Control first. Power later.",
  "Just you versus gravity, The floor is waiting.",
  "Strength is built in motion, not comfort.",
  "Discipline beats motivation when motivation fades.",
  "Every rep is a step closer to mastery.",
  "Pain is temporary, pride is permanent.",
  "Consistency is the bridge between goals and results.",
  "Your only competition is the person you were yesterday.",
  "Movement is freedom; your body is your gym.",
  "Push yourself, because no one else will do it for you.",
  "Small daily wins build monumental strength.",
  "The harder the struggle, the sweeter the gain.",
  "You don’t need equipment, just determination.",
  "Your limits are only as real as you believe them to be.",
  "Sweat is proof that you are trying.",
  "Control your body, control your life.",
  "The journey is the reward — one rep at a time.",
];
